// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXVoyD0NYCCiggq4P6vhLGSlNrkCDWBdI',
    appId: '1:102535343335:web:35eccf266598894e2dc642',
    messagingSenderId: '102535343335',
    projectId: 'health-app-6cc60',
    authDomain: 'health-app-6cc60.firebaseapp.com',
    storageBucket: 'health-app-6cc60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDin7wVkXx4XTbpO79hkC3jGM68p31bxCM',
    appId: '1:102535343335:android:f36ad9fd9a9c309d2dc642',
    messagingSenderId: '102535343335',
    projectId: 'health-app-6cc60',
    storageBucket: 'health-app-6cc60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPvJbFP3eQVBbSKCqcKPuDwXq_RFGJQw',
    appId: '1:102535343335:ios:bf1b22738fe46ef52dc642',
    messagingSenderId: '102535343335',
    projectId: 'health-app-6cc60',
    storageBucket: 'health-app-6cc60.appspot.com',
    iosBundleId: 'com.example.kesehatanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfPvJbFP3eQVBbSKCqcKPuDwXq_RFGJQw',
    appId: '1:102535343335:ios:bf1b22738fe46ef52dc642',
    messagingSenderId: '102535343335',
    projectId: 'health-app-6cc60',
    storageBucket: 'health-app-6cc60.appspot.com',
    iosBundleId: 'com.example.kesehatanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXVoyD0NYCCiggq4P6vhLGSlNrkCDWBdI',
    appId: '1:102535343335:web:f27435e5e548f3252dc642',
    messagingSenderId: '102535343335',
    projectId: 'health-app-6cc60',
    authDomain: 'health-app-6cc60.firebaseapp.com',
    storageBucket: 'health-app-6cc60.appspot.com',
  );

}